### ISSUE TITLE
Add touch controls like in the DeSmuMe DS core

### ISSUE THREAD

**Issue by hyarsan** [libretro/citra#10]
Add pointer type: touch, just like in the DeSmuMe core core-options. It makes the pointer go to your cursor ( Or where you tapped ) instead of the pointer that follows your cursor. The pointer also goes invisible, after you restart the core first. ( Pointer = the inverted box )

I would love this functionality!

**Comment by j-selby** [comment]
I attempted this before, but LibRetro doesn't report absolute values for mouse inputs, and I haven't found a device which satisfies RetroArch, so I doubt this will happen from me.

**Comment by j-selby** [comment]
Implemented in 90449fe64faf24fc974fdce322f3fa49e454311a - see how that goes for you!
