### ISSUE TITLE
Swap Screen Shortcut for Steam Deck

### ISSUE THREAD

**Issue by LeakedDave** [libretro/citra#104]
Please pass through the F9 hotkey or similar to swap screen. We can use Steam to bind a back shoulder button (R4) to F9 to swap screens. Seems like F9 is mute/unmute on RetroArch, maybe need a different key. Or just make it bindable in the Quick Menu with default not being set. Cheers.

**Comment by m4tsa** [comment]
Solved by 55ffed1f14a0c0a34bfdf367b8506da36b2cd9ca

I had to make it share the button with *Home* as there was no free buttons left, but Home does not actually activate a Home menu so it should be fine.

**Comment by Rolen47** [comment]
That works, but you have to hold down the button for the screens to stay swapped. It's incredibly awkward. Could it be changed to a toggle?
