### ISSUE TITLE
This core has a bug that disables the touch cursor if you start the core with only one screen in some games

### ISSUE THREAD

**Issue by i30817** [libretro/citra#111]
As in the title. A example of a game where this happens is Noitu Love - Devolution.

To reproduce start the core with only the 'top' screen in this game, and even if you use a switch toggle/press button to switch screens you'll see a 'tap to select' screen, then you press enter and the menu appears... but the touch cursor doesn't.

To workaround it, have both screens on the start of the emulator core.

**Comment by Inno2d** [comment]
Second this, I was going crazy trying to figure out why the pointer didn't show up on switching to the second screen when it does so in Citra standalone and in the Retroarch NDS cores. Thanks for posting the workaround, at least starting with dual screens then switching to single screen retains the visible pointer, although it's a bit annoying having to start games like this every time.

**Comment by i30817** [comment]
This got (accidentally) fixed by someone actually figuring out the real cause because it was causing bugs in scummvm and dosbox.

It was the wayland driver not having cursor capture implemented. Recently there was a series of commits last week implementing that and fixing some crashes from corner cases like having no cursor and game mode toggle crashing.

I also found out you can control the cursor in this core with no cursor with the retroapad l-pad (directions) and L3 (click) if you have it configured.

**Comment by i30817** [comment]
The PR for historical interesting, checking for possible regressions in the future:

https://github.com/libretro/RetroArch/pull/15103
