### ISSUE TITLE
Pointer size not consistent with Default Top-Bottom Screen

### ISSUE THREAD

**Issue by hyarsan** [libretro/citra#13]
The size of the pointer is not consistent with the Default Top-Bottom Screen on the Big Screen, Small Screen layout. Compare the pointer on these screenshots.

![mario kart 7 usa decrypted -171029-213733](https://user-images.githubusercontent.com/32988993/32148195-63943f20-bcf3-11e7-957b-6873f4fe83c8.png)
![mario kart 7 usa decrypted -171029-213656](https://user-images.githubusercontent.com/32988993/32148196-63b01f56-bcf3-11e7-80c0-d7f7128b1520.png)

**Comment by j-selby** [comment]
This is intentional. It is meant to be a percentage of the screen size.

**Comment by hyarsan** [comment]
Okay, but the pointer feels slower because of that. ( The pointer is slower because that there are more pixels so it is slower if you know what I mean )

**Comment by j-selby** [comment]
Partially fixed by cdae5ed, pointer size is still relative to the framebuffer, but speed is now correct.
