### ISSUE TITLE
Frame limiter should be off by default

### ISSUE THREAD

**Issue by hyarsan** [libretro/citra#15]
The frame limiter should be off by default because fast forward works properly if it's off.

**Comment by j-selby** [comment]
This is a issue tracker, not a feature request forum. Please leave comments like this to the LibRetro forums or other. Thanks!

**Comment by hyarsan** [comment]
Isn't this an bug because fast forward doesn't work? I'll try it myself then...

**Comment by j-selby** [comment]
Fast forwarding works fine, if you have the limiter disabled. This isn't a bug.

**Comment by hyarsan** [comment]
Yeah, but shouldn't it thus be disabled by default then?

**Comment by j-selby** [comment]
Eh, don't think so. The whole point of the limiter is to prevent running overspeed in a general state, so I think I'll leave defaults like this on. I might reevaluate later.

**Comment by hyarsan** [comment]
Doesn't RetroArch already limit the FPS? I don't think there is a need to limit the already limited FPS. I haven't had any issue with over speed with it turned off. Is there also a reason why slow motion just lowers the pitch of the sound but nothing else?

As you can see about this fidget spinner ( It runs full speed haha, the recording software doesn't record it accurately. )

https://1drv.ms/v/s!AvB-c2zUfIalrBbuJ_43mN-5EHyv

RetroArch already limits the FPS properly. So there is no need to limit the already limited FPS from the Citra core.

**Comment by hyarsan** [comment]
Umm, can you re-open this issue so people are aware of this or do you still not understand what I mean?
