### ISSUE TITLE
Core option to toggle if the fake cursor is visible or not

### ISSUE THREAD

**Issue by hyarsan** [libretro/citra#18]
Can we please have a core option to toggle if the fake inverted cursor is visible? I am not sure why you would want to see it if you are in windowed mode.

**Comment by j-selby** [comment]
This is a bug tracker, not a feature request forum. Please post such comments to the LibRetro forums or elsewhere. Thanks!

**Comment by hyarsan** [comment]
No offense, but I don't get why this is a feature. I am not asking for much. I will put it on the forums later anyway.
