### ISSUE TITLE
Core option that toggles between the new and old behaviours of the cursor

### ISSUE THREAD

**Issue by hyarsan** [libretro/citra#19]
The new behavior for mouse isn't the best, so can we have a way to toggle between the old and new one? Old one should be called "mouse" and the new one "touch" :P

**Comment by j-selby** [comment]
This is a bug tracker, not a feature request forum. Please post such comments to the LibRetro forums or elsewhere. Thanks!

**Comment by hyarsan** [comment]
The last time I tried to request anything Citra Libretro related, they just told me to go make a Github account...
