### ISSUE TITLE
Where is the fake mouse supposed to be located relative to the cursor?

### ISSUE THREAD

**Issue by hyarsan** [libretro/citra#20]
https://1drv.ms/i/s!AvB-c2zUfIal2xob0TaNIvyaovG4

The cursor isn't in the top left, middle OR bottom right of the fake cursor... what? Can we not have it be in the middle? Or even better, whatever location Citra Upstream uses?

**Comment by j-selby** [comment]
Closing this issue, as the issue template has not been completed.

---

This behaviour is intentional. Your mouse inside the cursor is relative to the screen.

**Comment by hyarsan** [comment]
Really? Why did you have to close this issue because I didn't put everything in the right order? I gave enough info and even made a gif to show what I mean? What's wrong with asking for more info instead of just asking me to re do it?

Anyways, Windows 10 64-bit... if it's even relevant. It just doesn't make sense, what's wrong with centering or putting the cursor on the top right relative to the mouse?

No offense, but really?... don't just copy and paste, you know better than that.

**Comment by j-selby** [comment]
The reason why we have issue templates is because it makes communication quite a bit easier. This isn't meant to prevent the issue from being discussed, but we can only do so much with one line of description. What if this was a platform specific issue? What if this was tied to a specific commit?

The .gif, while appreciated, was too unwieldy for use - it was 30mb, and took forever and a day for me to load. Better examples would be a few images highlighting the inconsistency.

**Comment by hyarsan** [comment]
Thank goodness, no copy & paste! :) Even the gif is too big? I originally wanted to compress it, but even the tool couldn't handle it.

@BreadFish64 did you dislike because you were salty of that melonDS issue?

**Comment by hyarsan** [comment]
![citra_libretro_issue](https://user-images.githubusercontent.com/32988993/35449532-99ab64ac-02bd-11e8-9962-e769fe520804.png)

As you can see, the fake cursor isn't completely exactly where the cursor is. The more you go left, right, up or down from the middle the more off it is. Shouldn't the cursor stay properly relevant to the fake cursor? I don't know anything about the Citra source code, so I am not sure if the point of the cursor is supposed to be in the top left corner of the fake? Okay, so I just asked someone on Citra Discord and it guess it should be a cross-hair instead.

**Comment by hyarsan** [comment]
Mockup:
![3dscrosshair](https://user-images.githubusercontent.com/32988993/35625043-2eb33d00-0691-11e8-9c39-8d86209ef0db.png)

Doesn't that look nicer than the square? It would be more precise and looks nicer.

**Comment by j-selby** [comment]
Going to need someone with oGL skills to fix this up. The cursor position being bounded to the canvas was intentional as if it left that bottom screen (i.e the arms of the cross, or a side of the current box) leaves snow in areas that are not glCleared (which had to be disabled due to buggy Intel drivers). This isn't likely going to be fixed anytime soon - sorry.

**Comment by j-selby** [comment]
For reference, this issue could be fixed with the following:

mouse_tracker.cpp @ 134:
```
    // Map the mouse coord to the bottom screen's position (with a little margin)
    projectedX =
        bottomScreen.left + projectedX * (bottomScreen.GetWidth());
    projectedY = bottomScreen.top +
                 projectedY * (bottomScreen.GetHeight());
```

Again though, this will conflict with the disabled glClear.

**Comment by hyarsan** [comment]
The cursor is bounded to the screen? That's great, I never said it shouldn't. Maybe the arms that are offscreen would not be rendered?

**Comment by j-selby** [comment]
Culling the edges of the cursor is out of my skill level, sorry - going to need someone else to take a look at this. Was planning to provide options to hide the cursor, but unrelated to this issue.

**Comment by hyarsan** [comment]
what if it behaves like it does right now, but just looks like a cross? that would be fine :)

**Comment by j-selby** [comment]
Should be fixed now. See how this goes!

**Comment by hyarsan** [comment]
hm, I can't check it out because it's broken now for Windows ( 10 64-bit ) but I'm sure it's great :)

**Comment by j-selby** [comment]
@hyarsan use RetroArch nightly

**Comment by hyarsan** [comment]
hmm thanks :)
