### ISSUE TITLE
Mouse cursor sticky corners

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/citra#23]
The cursor movement isn't limited by the bottom screen area when using a real mouse.
It's completely relative and you have to do the same amount of movement back that you made out of the screen borders.

[I guess it's not passing through that function?](https://github.com/libretro/citra/blob/master/src/citra_libretro/input/mouse_tracker.cpp#L63)

**Comment by j-selby** [comment]
It is passing though those functions. Mouse movement is reported by LibRetro in a absolute fashion, so unless I use previous mechanisms to track mouses (which had a whole host of other issues). If you use RetroArch in a windowed mode with the cursor visible, this will make more sense.

**Comment by Tatsuya79** [comment]
It can be relative or absolute in Libretro.
[I could limit the range in Nestopia here like that.](https://github.com/libretro/nestopia/commit/17d28c42ab6589aab290117efa19713e7080f826)
Sorry I can't do it myself and test it as I only compile with msys2.

**Comment by j-selby** [comment]
Citra works fine with msys2/mingw64. As I said above, we tested using the relative cursor before, but that solution came with a whole other set of issues. This would have to be a non-default option.
