### ISSUE TITLE
RA Citra Core eating more RAM as time passes

### ISSUE THREAD

**Issue by LOuroboros** [libretro/citra#24]
First of all, I must say that I'm not entirely sure if this issue is on the RetroArch Frontend's end or if it's caused by the Citra Core. Please, if I'm submitting this report in the wrong repository, point me in the correct direction.

**Version**: Latest version of the Citra Core downloaded from the Core Updater Option inside RetroArch.

**Issue**: RetroArch's Citra and Citra Canary Cores seem to be eating more and more RAM the more time I play a videogame. It starts eating around 800 MBs and it doesn't stop until it crashes along Windows Explorer.

Sometimes it simply makes the Windows Explorer unstable and restarting its process is more than enough, but some others it makes the whole screen look grey forcing the user to restart the PC.

**Specs**: Intel Celeron N2840, 2 GBs of RAM, Windows 8.1 _(64 Bits)_

At first, it eats around 800 MBs, as I mentioned:
![racpusagebeginning](https://user-images.githubusercontent.com/4485172/37433426-a92cbfe4-27ba-11e8-8b0b-127e64f18712.png)

But if you play a videogame for like, 30 minutes or so, it can eat this much: 
![racpusage](https://user-images.githubusercontent.com/4485172/37429209-6d74caee-27ad-11e8-8d0e-aaf32db6c46e.png)

**Comment by j-selby** [comment]
Does this occur with standalone?

If you only have 2gb of RAM, you aren't likely going to have a good time, sorry.

**Comment by LOuroboros** [comment]
No, it doesn't happen with standalone versions.

About the gaming experience itself, don't worry, it's pokémon and I'm only interested in experiencing the game. The framerate I'm currently getting is more than enough.

**Comment by j-selby** [comment]
Ok. GPU shaders are still not merged into nightly, so I suggest you provide a **detailed** explanation of the issue up over at the responsible PR @ https://github.com/citra-emu/citra/pull/3499, including GPU info, drivers, logs, and so on. Make sure to test with Standalone Canary.

Thanks!
