### ISSUE TITLE
Canary 29+ fails to build with "-DENABLE_SDL2=0"

### ISSUE THREAD

**Issue by SupervisedThinking** [libretro/citra#25]
Since https://github.com/libretro/citra/blob/master/src/dedicated_room/citra-room.cpp relies on SDL.h the compilation is terminated when you set "-DENABLE_SDL2=0" as cmake flags. It compiles without errors when you set "-DENABLE_SDL2=1"

// Copyright 2017 Citra Emulator Project
// Licensed under GPLv2 or any later version
// Refer to the license.txt file included.

#include <chrono>
#include <iostream>
#include <memory>
#include <regex>
#include <string>
#include <thread>
#define SDL_MAIN_HANDLED
**#include <SDL.h>**
#include <glad/glad.h>

**Comment by j-selby** [comment]
https://github.com/citra-emu/citra/issues/3538

**Comment by i30817** [comment]
Funny, the ppa of the stable build is failing with a different error:

https://launchpadlibrarian.net/365016888/buildlog_ubuntu-bionic-amd64.libretro-citra_0.1-r201804130947-7e78ed1-10~ubuntu18.04.1_BUILDING.txt.gz

**Comment by j-selby** [comment]
@i30817 I don't support 3rd party build environments here. That is an issue with their build script.

**Comment by j-selby** [comment]
@SupervisedThinking does this issue still occur? See https://github.com/citra-emu/citra/pull/3634

**Comment by SupervisedThinking** [comment]
it's fixed 👍
