### ISSUE TITLE
Newest Build cannot be used

### ISSUE THREAD

**Issue by Papermanzero** [libretro/citra#27]
Download the newest build and try to start the core.
An error occurs with the canary as well as the stable build.
Log:

[ERROR] Failed to open libretro core: "C:\Retroarch\cores\citra_libretro.dll"
[ERROR] Error(s): unknown error 127
[INFO] [GL]: VSync => on
[INFO] [WGL]: wglSwapInterval(1)

**Comment by j-selby** [comment]
You have not filled out the template correctly for this issue. If this issue still exists, please make sure to fill out EVERYTHING. Thanks!
