### ISSUE TITLE
Citra crashes when closing content

### ISSUE THREAD

**Issue by 777sha** [libretro/citra#29]
Windows 10 - AMD Radeon RX 480

Retroarch 1.7.2 nightly build 2018-24-03
Latest version of Citra canary

Citra crashes when hitting "close content" (pressing escape and exiting both the core and RetroArch doesn't cause any issues)

Log file : https://pastebin.com/GD0tWau2
Console output : https://pastebin.com/QCYf3F9x

**Comment by j-selby** [comment]
Does this issue occur with nightly?

**Comment by 777sha** [comment]
It doesn't crash anymore in 2018-03-25 nightly
