### ISSUE TITLE
Use LibRetro provided storage paths

### ISSUE THREAD

**Issue by j-selby** [libretro/citra#3]
**Background**

Right now, Citra-LibRetro defaults to the same filesystem locations for storing data as Citra upstream does.  While this means that savedata can be shared seamlessly, it means that people preferring to store data in LibRetro paths (and keep save data uniformly stored) miss out.

**Problem**

Currently, Citra's `file_util` solution bakes in paths based upon the target operating system, and these cannot be configured by frontends.

**Proposed solution**

The following steps should be taken:

- [ ] Provide a mechanism for configuring file paths (upstream)
- [ ] Implement this new interface in Citra-LibRetro

**Comment by blackwind** [comment]
Citra saves are stored as a series of files and folders. When this is implemented, will this core condense them into a single `.srm` file? And if so, will it be possible to convert existing saves to the new format?

Currently thinking about starting a 3DS game in RetroArch, but will gladly wait if my save will end up being useless in a future update.

**Comment by j-selby** [comment]
@blackwind Not likely, no. We are working through some changes upstream which should maybe make this easier.
