### ISSUE TITLE
Ever Oasis crash on startup

### ISSUE THREAD

**Issue by 777sha** [libretro/citra#30]
Windows 10 - AMD Radeon RX 480
Retroarch 1.7.2 nightly build 2018-24-03
Latest version of Citra canary

Not sure if I should have posted this issue on the original Citra repo.

When loading the game "Ever Oasis" Retroarch crashes. I've tried 2 different decrypted dumps of the game.

![everoasis](https://user-images.githubusercontent.com/18407984/37867642-d31aff26-2f9b-11e8-8f27-4ab86b947dce.PNG)

RA log : https://pastebin.com/EAZDLDpW

**Comment by j-selby** [comment]
Does this occur with regular Citra?

**Comment by Papermanzero** [comment]
No, it does not occur. Same issue here

**Comment by j-selby** [comment]
Please use nightly then for the meantime. If this occurs in standalone Citra-Canary, please report it there. Thanks!

**Comment by 777sha** [comment]
Just tested, it does boot up in standalone canary.

**Comment by Papermanzero** [comment]
Citra standalone and canary standalone are working fine. Libretro still does not work

**Comment by j-selby** [comment]
@Papermanzero are you running AMD hardware?

**Comment by Papermanzero** [comment]
My hardware:
Windows 10 x64
Intel i7 4790
Nvidia 760 GTX

**Comment by j-selby** [comment]
@Papermanzero are you using RetroArch shaders? Could you reset your RetroArch configuration and see if the problem still occurs?

**Comment by 777sha** [comment]
This is still happening btw not sure why it was closed. I'm also confident it has nothing to do with shaders.

**Comment by j-selby** [comment]
@777sha Saying it is still happening but not giving any evidence/diagnostics is just a douche move. If you are affected by this issue, can you please create a new one, filling out the template completely?

**Comment by 777sha** [comment]
Sorry I thought my description of the issue was enough but it seems you want a backtrace as well in the template but I'm not capable of providing one. I didn't mean to be annoying keep up the good work.
