### ISSUE TITLE
Buildbot's compile crashes when compiling linux build x64 generic core

### ISSUE THREAD

**Issue by telanus** [libretro/citra#34]
Buildbot's compile crashes when compiling linux build x64 generic core

Crashlog
http://p.0bl.net/182937

**Comment by j-selby** [comment]
Canary is provided in a best-effort basis - as it is automated, we cannot guarantee that it compiles or works. Issues should only be raised for nightly.

---

This specific issue has been resolved, but next time, please don't open issues for canary. Thanks!
