### ISSUE TITLE
RetroArch freeze upon closing core

### ISSUE THREAD

**Issue by budtz** [libretro/citra#39]
ok ill try again.

using version 746e2fb of canary

i dont know what a backtrace is but retorarch crashes whenever i exit a game with this version. i am using version 1.7.3 stable.

also loading majoras mask leads to a crash

and then there is the missing text in metroid.

**Comment by j-selby** [comment]
Somewhat better, though still missing alot of information.

What are your system specs?

I am going to need a backtrace from gdb or Visual Studio for the crashes. I suggest you do some research.

Can I have a log for the Majora's Mask crash?

Does upstream's Canary builds also exhibit the Metroid issue?

**Comment by budtz** [comment]
Ok Thx ill work on that. 

For now: system spec is windows 10 latest Build Gtx 1060 latest driver. Haswell core i5.

Both issues in zelda metroid do not happen in the standalone version  of citra if thats what you mean. Zelda loads and metroid has text. I have tried different settings to no avail. But i have not gone through all settings systematicly.

**Comment by hyarsan** [comment]
Same happens here with Close Content or by exiting RetroArch. I'll do a backtrace as well.

**Comment by TradeDraft** [comment]
I also have the Same Problem and with the Stable 1.7.3 Version with latest Citra Cores

**Comment by j-selby** [comment]
@TradeDraft Then please provide a backtrace. Nobody has given me one, so I can't help with this issue. This is a developer issue ticketing system, not a user one.

**Comment by TradeDraft** [comment]
@j-selby how do I do a BackTrace so I can do one?

**Comment by j-selby** [comment]
@TradeDraft gdb/dr mingw? Again, developer board, by posting here you should have basic debugging skills.

**Comment by TradeDraft** [comment]
I used the Debug in Retro Arch and got these Reports.

Citra Core:

https://www.sendspace.com/file/arg46x

Citra Canery Core:

https://www.sendspace.com/file/y7e2fm

**Comment by j-selby** [comment]
@TradeDraft That log doesn't really tell me anything, sorry. Again, going to need a proper debugger hooked up.

**Comment by BParks21** [comment]
Same problem for me.

**Comment by j-selby** [comment]
This is now fixed as of b7116d6. Have fun!

**Comment by BParks21** [comment]
@j-selby So this is for canary, can i download this through the online updater already?

**Comment by j-selby** [comment]
@BParks21 haven't updated Canary. Give me 24 hours or so for me to push a new build.

**Comment by BParks21** [comment]
Ok
