### ISSUE TITLE
Fake cursor disappears after doing fullscreen toggle

### ISSUE THREAD

**Issue by hyarsan** [libretro/citra#40]
I'm using Windows 10 64-bit, on the latest Citra Nightly Libretro and Citra Canary Libretro, the fake cursor disappears when doing a full screen toggle in RetroArch.

![tri force heroes e -180521-125228](https://user-images.githubusercontent.com/32988993/40304342-be370108-5cf6-11e8-9837-0d80a92690af.png)
Now I press fullscreen toggle....
![tri force heroes e -180521-125640](https://user-images.githubusercontent.com/32988993/40304360-c8902e86-5cf6-11e8-9769-d2fd4997bbc7.png)
As you can see, the cursor disappeared but it still functions as it's supposed to.

**Comment by BParks21** [comment]
I was just about to report this. Same issue here.

**Comment by j-selby** [comment]
@BParks21 Don't need you to comment for +1s, thanks. There are reactions for a reason.

**Comment by j-selby** [comment]
Fixed as of 8dc3431. Have fun!
