### ISSUE TITLE
language game is not correct, can not choose language or correct user language is not detected

### ISSUE THREAD

**Issue by legluondunet** [libretro/citra#42]
Hello, I'm french and when I launch multi5 game with citra libretro module, the game always starts in english, I can not choose the french language anywhere or the module doesn't automatically detect my language environment. 

tested roms: 
The Legend of Zelda - A Link Between Worlds-Europe-Multi5
Super Mario 3D Land (EUR) 

Thank you for your help.

Module version: 85e47f1

**Comment by j-selby** [comment]
This is based on your system files, which pulls that info from the 3DS console in which you dumped your files from.

No plans to add UI to change this in the core, as I'm not happy making dangerous modifications to user files.

**Comment by legluondunet** [comment]
Do you think it would be more relevant to request this feature directly from the main Citra Github page?

**Comment by j-selby** [comment]
You can change the language already in upstream's Citra. See #12 for what I might eventually do.

**Comment by legluondunet** [comment]
My feature request is exactly a duplicate of #12 , Citra Libretro module should use the language and user name from the retroarch interface. I'm happy you planned to add this feature.
