### ISSUE TITLE
Libretro Citra breaks on Majora's Mask 3DS while upstream doesn't

### ISSUE THREAD

**Issue by billywade** [libretro/citra#43]
When I try to boot Majora's Mask 3D, Retroarch crashes with the following error:
```
[libretro ERROR] HW.Memory @ core/memory.cpp:Read:154: unmapped Read32 @ 0x0000D304
[libretro ERROR] HW.Memory @ core/memory.cpp:Read:154: unmapped Read32 @ 0x0000D308
[libretro ERROR] HW.Memory @ core/memory.cpp:Read:154: unmapped Read32 @ 0x0000D30C
[libretro ERROR] HW.Memory @ core/memory.cpp:Read:154: unmapped Read32 @ 0x0000D310
[libretro ERROR] HW.Memory @ core/memory.cpp:Read:154: unmapped Read32 @ 0x0000D314
[libretro ERROR] HW.Memory @ core/memory.cpp:Read:154: unmapped Read32 @ 0x0000D318
[libretro ERROR] HW.Memory @ core/memory.cpp:Read:154: unmapped Read32 @ 0x0000D31C
[libretro ERROR] HW.Memory @ core/memory.cpp:Read:154: unmapped Read32 @ 0x0000D320
[libretro ERROR] HW.Memory @ core/memory.cpp:Read:154: unmapped Read32 @ 0x0000D324
[libretro ERROR] HW.Memory @ core/memory.cpp:Read:154: unmapped Read32 @ 0x0000D328
[libretro ERROR] HW.Memory @ core/memory.cpp:Read:154: unmapped Read32 @ 0x0000D32C
[libretro ERROR] HW.Memory @ core/memory.cpp:Read:154: unmapped Read32 @ 0x0000D330
[libretro ERROR] HW.Memory @ core/memory.cpp:Read:154: unmapped Read32 @ 0x0000D334
[libretro ERROR] HW.Memory @ core/memory.cpp:Read:154: unmapped Read32 @ 0x0000D338
[libretro ERROR] HW.Memory @ core/memory.cpp:Read:154: unmapped Read32 @ 0x0000D33C
[libretro ERROR] HW.Memory @ core/memory.cpp:Read:154: unmapped Read32 @ 0x0000D340
[libretro ERROR] HW.Memory @ core/memory.cpp:Read:154: unmapped Read32 @ 0x0000D344
[libretro ERROR] HW.Memory @ core/memory.cpp:Read:154: unmapped Read32 @ 0x0000D348
[libretro ERROR] HW.Memory @ core/memory.cpp:Read:154: unmapped Read32 @ 0x0000D34C
[libretro ERROR] HW.Memory @ core/memory.cpp:Read:154: unmapped Read32 @ 0x0000D350
```
repeating indefinitely. I tried dumping the ROM twice to get it running but no luck. Additionally, upstream runs this fine. I'm using the latest commit of the Libretro fork and `master-7f983fe7' of upstream. What all do you guys need from me?

EDIT: it looks like this problem was fixed in upstream with [this commit](https://github.com/citra-emu/citra/pull/1794/files), but the memory.cpp file here is unrecognizable compared to there, and the class where the fix resides (void MemoryInit) doesn't have an analog in the libretro version.

**Comment by twinaphex** [comment]
Hi @j-selby , is this something you'd like to look into please?

**Comment by billywade** [comment]
@twinaphex This is the second libretro issue I've pushed recently and you've been the first to get triage both times. Thanks for the help.

**Comment by j-selby** [comment]
@billywade Could I please have a FULL log from RetroArch? Thanks.

**Comment by billywade** [comment]
@j-selby You got it.
[log.txt](https://gist.github.com/billywade/af72da957abad4c5bb391727fad79447)

**Comment by billywade** [comment]
Just an update, I recently had the same unmapped read error in  Animal Crossing: New Leaf, but later in the game.

**Comment by budtz** [comment]
New version has no audio. When downgrading audio is back. The region fixes makes it possible to load zelda now but it crashes and exits once i have to type in my name. Also metroid seamus returns works in new version. It was unplayable before because game couldnt progress when u got an item.

**Comment by j-selby** [comment]
@budtz if you have other issues, please post them elsewhere - thanks!

**Comment by j-selby** [comment]
Can OP confirm that this issue is resolved? Thanks!

**Comment by budtz** [comment]
Sorry for the messy post. ill try and test as soon as i can download the new version from within retroarch

**Comment by budtz** [comment]
Zelda works now. All issues I had (that are not present in upstream) are resolved in this build.

thx for the work

**Comment by billywade** [comment]
@j-selby as it happens, my ISP is having issues so I'm not able to download the latest git. When I get internet back, I'll verify that the issue's fixed. Thanks a ton for getting it fixed, though! Given what budtz says, I figure it's fine, I just want to check.

**Comment by j-selby** [comment]
Received other reports that this issue has been resolved. Feel free to reopen if this isn't the case. Thanks!
