### ISSUE TITLE
[FEATURE REQUEST] Allow mapping toggle of [citra_swap_screen] to gamepad

### ISSUE THREAD

**Issue by billywade** [libretro/citra#44]
It would be a massive quality of life improvement to be able to toggle which screen is prominent without having to leave the game. It would make it both easier to use single-screen and the dual screen layouts.

**Comment by j-selby** [comment]
This is a frontend issue, not a core one. This should be implemented by RetroArch/whatever.

Closing.

**Comment by billywade** [comment]
Understood. I'll take it higher up.

**Comment by billywade** [comment]
@j-selby They closed my issue, saying it's a core issue.
