### ISSUE TITLE
libretro core does not load aes_keys.txt

### ISSUE THREAD

**Issue by flibitijibibo** [libretro/citra#49]
Citra recently added support for encrypted games:

https://github.com/citra-emu/citra/pull/4020

The catch is that you need to provide your own decryption keys, located at `USERDIR/sysdata/aes_keys.txt`. While this works with the Qt and SDL2 interfaces, it seems the libretro core does not init the keys when loading an encrypted game, resulting in failure to read the file.

Unfortunately that's about all I have to work with; I threw the file in both the libretro location (which for me is just `GAMEFOLDER/Citra/sysdata/`) and the Citra default location (`$XDG_DATA_HOME/citra-emu/sysdata`) and neither seems to work. That said, by default Citra is supposed to generate the folder if it doesn't exist, and strace suggests the folder is not being queried at all.

Attempting to compile `master` does not appear to work because the submodules are out of sync with their origins ("Server does not allow request for unadvertised object"), and the buildbot version doesn't have symbols, so I can't check to see if the core is calling `HW::AES::InitKeys`. The two things I would check out, though I'm pretty sure both of these are done in common code:

- The `sysdata` folder is wrong or not set at all
- `HW::AES::InitKeys` is never called

**Comment by j-selby** [comment]
Citra-LibRetro hasn't been rebased for this patch.

**Comment by flibitijibibo** [comment]
Oh, my mistake! I saw the merge in the logs but I hadn’t looked at HEAD at all... for reference, this is what I saw:

https://github.com/libretro/citra/commit/84fc8eaaba35542e602c002e658cf09e3169f6ce

**Comment by j-selby** [comment]
Can you test if this has been fixed now? Thanks!

**Comment by flibitijibibo** [comment]
Latest build fixes this, thanks!
