### ISSUE TITLE
ARM64 Dynarec for Citra

### ISSUE THREAD

**Issue by ManiManitasT210** [libretro/citra#54]
Hi.

This is needed in order to have it running at (near) full speed on the following platforms:

- Nintendo Switch (through Horizon OS and/or Lakka OS).

- Nvidia Shield TV.

- Mobile phones/tablets (Android and iOS devices).

- Raspberry Pi 3B+.

If needed, a bounty can be created.

https://www.bountysource.com/issues/66775521-jit-arm64-dynarec-for-citra

**Comment by Datamats** [comment]
This is something that should be implemented on [dynarmic](https://github.com/MerryMage/dynarmic) and not on the libretro core for Citra, You're probably better off asking them instead

**Comment by ManiManitasT210** [comment]
i saw in the n64 bounty natinusala did it in libretro/parallel64. so i thought it was ok.
