### ISSUE TITLE
RetroArch crashes when game is unloaded

### ISSUE THREAD

**Issue by blackwind** [libretro/citra#6]
When a game is loaded via this core, trying to load another game (whether it's through this core or any other core) causes RetroArch to reliably crash. I read about this issue somewhere online months back when the core was first released, and it's still a problem as of a0a4d698, at least on Windows 10 1703 using RetroArch 1.6.7 x86_64.

**Comment by j-selby** [comment]
Yeah, I know of this as well. Haven't had the chance to work out where it is coming from.

**Comment by j-selby** [comment]
@blackwind does it still occur with the latest RetroArch/core?

**Comment by blackwind** [comment]
Right now, all I'm getting is "Failed to open libretro core".

**Comment by j-selby** [comment]
@blackwind try with RetroArch nightly?

**Comment by blackwind** [comment]
Same thing in nightly.

**Comment by j-selby** [comment]
Failed to open libretro core? That sounds like a problem with your installation of RetroArch. Have you updated the entire application, or just the .exe?

**Comment by blackwind** [comment]
Entire application. All other cores continue to work as normal.

**Comment by 777sha** [comment]
I'm on 8th march nightly build

I can load the citra canary core in this build (but not on vanilla 1.7.1), but RetroArch crashes when exiting games too.

**Comment by j-selby** [comment]
This should be fixed with 8adf223. When the buildbot finishes, could this be tested? Thanks!

**Comment by blackwind** [comment]
Confirmed fixed. Cheers!
