### ISSUE TITLE
LClick & RJoystick button no longer tap screen

### ISSUE THREAD

**Issue by Link-Satonaka** [libretro/citra#7]
Testing against the latest commit ( https://github.com/libretro/citra/commit/c892166279c83b605e53223f459be98ec022e324 )

This functionality no longer works for me. The binary provided by the retroarch core downloader, however, does work. This leads me to believe that the functionality introduced in commit https://github.com/libretro/citra/commit/ace0be96c9a308cf19b86d97b610c18a76bbb50a was lost by subsequent commits- at least for linux.

I run archlinux x86_64 and I use the aur package (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libretro-citra-git)

**Comment by j-selby** [comment]
Think I have an idea of what is going on. Does moving the mouse still work?

**Comment by j-selby** [comment]
Fixed as of 1823304b34376e65a8d16fffbb04b10a9a00f1f7
