### ISSUE TITLE
Shaders don't work with 3DS citra TOP screen

### ISSUE THREAD

**Issue by retr0man** [libretro/citra#9]
Simple report: Graphic shaders will work with the 3DS bottom screen (the touch screen) but NOT the top screen. Since enhancing games in Retroarch is often times the highlight/benefit in using Retroarch as opposed to the standalone emulator itself, it is a shame that the main game screen isn't getting the same love as other games. Not sure 'why' the TOP screen isn't affected by shaders. Reporting on it now, etc.

**Comment by fr500** [comment]
That makes no sense
Are you running the top screen at higher internal resolution?

**Comment by retr0man** [comment]
Fr500... Sorry if I didn't explain it right. So.....say you set it up where the main non touch screen is on the bottom. Then shaders indeed work for that screen. I was testing this on native res. And by main screen I meant, if you are holding a real 3DS, the screen on top of the actual device. BUT, if I select "large screen, small screen", the touch screen displayed in the lower corner appears raised as signified by a shadow around the window and is affected by shaders whereas the much larger window is ignored by the shaders. If you switch it so that the bottom screen is prominent then it becomes the large screen, but for games like Space Harriet where the game itself is displayed on the main screen then the shaders only work on that limited small screen in the corner. If I choose the regular setup to mirror the 3DS where there are two matching screens (in size) then as long as the main game screen is reversed, setting it as the bottom, then it will get some shader love there. But for games like that, it would be nice if I could choose to have it as the larger screen since you are limited to that 50% in size. As a workaround, could the emulator core simply be updated so that if "large screen, small screen" is selected, then TOP or BOTTOM could be interchangeable? Say, by including in the option, 'TOP as BOTTOM' or 'BOTTOM as TOP' or something like that to avoid confusion. I can elaborate or distill this further if it helps. I was using the OpenGL driver on a windows 10 PC with compatible shaders, no CG or slang

**Comment by j-selby** [comment]
Sorry to reply late to this. From libretro's perspective, shaders are executed after rendering both screens, so this is a issue with your specific shader (most are designed to operate on small framebuffers, not >1080p ones which Citra can produce). Which shaders are you using which exhibit this issue?

**Comment by j-selby** [comment]
@retr0man is this still an issue, or should I close this?

Thanks!

**Comment by j-selby** [comment]
Closing, as no response from author.
